DROP VIEW IF EXISTS USER_MANI.CURATED_DATA.AIRLINES_WITH_LARGEST_DELAYS;
CREATE VIEW IF NOT EXISTS USER_MANI.CURATED_DATA.AIRLINES_WITH_LARGEST_DELAYS AS
(SELECT AIRLINES_RAW.AIRLINE, SUM(DELAY_COUNT) AS TOTAL_DELAY FROM
(SELECT AIRLINE, COUNT(DEPARTURE_DELAY)AS DELAY_COUNT
FROM "USER_MANI"."CURATED_DATA"."FLIGHTS"
WHERE DEPARTURE_DELAY != 0 AND DEPARTURE_DELAY IS NOT NULL
GROUP BY AIRLINE
UNION
SELECT AIRLINE, COUNT(ARRIVAL_DELAY) AS DELAY_COUNT
FROM "USER_MANI"."CURATED_DATA"."FLIGHTS"
WHERE ARRIVAL_DELAY != 0 AND ARRIVAL_DELAY IS NOT NULL
GROUP BY AIRLINE) AS DELAY
JOIN "USER_MANI"."RAW_DATA"."AIRLINES_RAW" AS AIRLINES_RAW WHERE DELAY.AIRLINE = AIRLINES_RAW.IATA_CODE
GROUP BY AIRLINES_RAW.AIRLINE ORDER BY SUM(DELAY_COUNT) DESC
);