DROP VIEW IF EXISTS USER_MANI.CURATED_DATA.CANCELLATION_REASONS_BY_AIRPORT;
CREATE VIEW IF NOT EXISTS USER_MANI.CURATED_DATA.CANCELLATION_REASONS_BY_AIRPORT as (
WITH
destination as (SELECT DESTINATION_AIRPORT as AIRPORT,
    CANCELLATION_REASON, COUNT(CANCELLATION_REASON) AS DEST_COUNT
FROM "USER_MANI"."CURATED_DATA"."FLIGHTS" WHERE CANCELLED = 1
GROUP BY DESTINATION_AIRPORT, CANCELLATION_REASON),

origin as (SELECT ORIGIN_AIRPORT as AIRPORT, CANCELLATION_REASON,
    COUNT(CANCELLATION_REASON) AS ORIG_COUNT
FROM "USER_MANI"."CURATED_DATA"."FLIGHTS" WHERE CANCELLED = 1
GROUP BY ORIGIN_AIRPORT, CANCELLATION_REASON)

select origin.AIRPORT, origin.CANCELLATION_REASON,
    (destination.DEST_COUNT+origin.ORIG_COUNT) as Total_Count
from origin, destination
where origin.AIRPORT = destination.AIRPORT and
    origin.CANCELLATION_REASON = destination.CANCELLATION_REASON
order by origin.AIRPORT ASC, origin.CANCELLATION_REASON ASC
);