DROP VIEW IF EXISTS 'USER_MANI.CURATED_DATA.ON_TIME_AIRLINES';
CREATE VIEW IF NOT EXISTS USER_MANI.CURATED_DATA.ON_TIME_AIRLINES as (
WITH
destination as (SELECT AIRLINE, COUNT(DEPARTURE_DELAY) AS TOTAL_COUNT,
SUM(CASE WHEN DEPARTURE_DELAY = 0 THEN 1 ELSE 0 END) AS ON_TIME_DEPT_COUNT,
((ON_TIME_DEPT_COUNT/TOTAL_COUNT)*100) AS ON_TIME_PER
FROM "USER_MANI"."CURATED_DATA"."FLIGHTS"
WHERE YEAR = 2015 AND DEPARTURE_DELAY IS NOT NULL
GROUP BY AIRLINE),

origin as (SELECT AIRLINE, COUNT(ARRIVAL_DELAY) AS TOTAL_COUNT,
SUM(CASE WHEN ARRIVAL_DELAY = 0 THEN 1 ELSE 0 END) AS ON_TIME_ARRI_COUNT,
((ON_TIME_ARRI_COUNT/TOTAL_COUNT)*100) AS ON_TIME_PER
FROM "USER_MANI"."CURATED_DATA"."FLIGHTS"
WHERE YEAR = 2015 AND ARRIVAL_DELAY IS NOT NULL
GROUP BY AIRLINE)

select AIRLINES_RAW.AIRLINE, (destination.ON_TIME_PER+origin.ON_TIME_PER) as TOTAL_ON_TIME_PER
from origin JOIN destination ON
origin.AIRLINE = destination.AIRLINE
JOIN "USER_MANI"."RAW_DATA"."AIRLINES_RAW" AIRLINES_RAW ON
AIRLINES_RAW.IATA_CODE = origin.AIRLINE
order by TOTAL_ON_TIME_PER DESC
);