DROP VIEW IF EXISTS USER_MANI.CURATED_DATA.UNIQUE_ROUTES_BY_AIRLINES;
CREATE VIEW IF NOT EXISTS USER_MANI.CURATED_DATA.UNIQUE_ROUTES_BY_AIRLINES as (
SELECT AIRLINES_RAW.AIRLINE, UNIQUE_ROUTE.UNIQUE_ROUTE_COUNT
FROM "USER_MANI"."CURATED_DATA"."AIRLINES_UNIQUE_ROUTE" AS UNIQUE_ROUTE
JOIN "USER_MANI"."RAW_DATA"."AIRLINES_RAW" AS AIRLINES_RAW WHERE
    UNIQUE_ROUTE.AIRLINE = AIRLINES_RAW.IATA_CODE
order by UNIQUE_ROUTE_COUNT DESC
);